apify/got-scraping

README.md
src/scraping-defaults.js
test/scraping-defaults.test.js

Based on the node docs. There are three default TLS 1.3 ciphers used.
```
There are only 5 TLSv1.3 cipher suites:
'TLS_AES_256_GCM_SHA384'
'TLS_CHACHA20_POLY1305_SHA256'
'TLS_AES_128_GCM_SHA256'
'TLS_AES_128_CCM_SHA256'
'TLS_AES_128_CCM_8_SHA256'
The first 3 are enabled by default. The last 2 CCM-based suites are supported by TLSv1.3 because they may be more performant on constrained systems, but they are not enabled by default since they offer less security.
```
This should just ensure that the `TLS_AES_256_GCM_SHA384` is used first.
closes #10

Scraping defaults - added more ciphers.

---

README.md
package.json
src/agent/transform-headers-agent.js
src/agent/wrapped-agent.js
src/hooks/proxy.js
src/index.js
test/agent.test.js
test/helpers/dummy-server.js
test/main.test.js
test/proxy.test.js

Moved from #25
The `should add custom headers` test is flaky, as the headers are fixed in the agent. ~~Will fix this asap.~~ Fixed.

Add TransfomHeadersAgent

---

src/hooks/custom-options.js
src/hooks/insecure-parser.js
src/hooks/options-validation.js
src/index.js
test/main.test.js

Enable insecure parser by default

---

package.json
src/hooks/proxy.js
test/proxy.test.js

This fixes issues with [`agent-base`](https://github.com/TooTallNate/node-agent-base) and [`https-proxy-agent`](https://github.com/TooTallNate/node-https-proxy-agent/blob/master/src/agent.ts)

Migrate to `hpagent`

---

package.json
src/agent/h1-proxy-agent.ts
src/hooks/proxy.ts
test/main.test.ts
test/proxy.test.ts

No promise usage = no unhandled rejections + no uncaught exceptions ;) Drop-in replacement for `hpagent`.
I had to revert `hpagent` on `got-scraping@2` because some proxies don't support `CONNECT` protocol, they're just usual web proxies.

Use own proxy agent

---

package.json
src/hooks/browser-headers.ts
src/hooks/fix-decompress.ts
src/index.ts
test/helpers/dummy-server.ts
test/main.test.ts

Figured out even a smarter solution, overriding the `response` event 😎
Closes #63

fix: be more lenient when decompressing

---

src/index.ts
src/types.ts

This solves an internally reported issue where using got-scraping would not include our custom options (like `proxyUrl`)

fix: allow passing extra options like `proxyUrl` on type level

---

.github/workflows/check.yml
.github/workflows/release.yml
jest.config.ts
src/agent/wrapped-agent.ts
test/agent.test.ts
test/main.test.ts

I've updated the GitHub workflows to use the new secrets synced from Doppler. And while I had this open, I've also updated the GitHub actions versions to get rid of the deprecation warnings, and I've added Node 18 and 20 to the test roster.

chore: use new workflow secrets, update GitHub Actions

---

src/resolve-protocol.ts

The way Node `v18.17` processes URLs causes that proxied connections are accessing `/` (pathname of the proxy), instead of the actual proxied URL. We could (should) eventually rewrite `got-scraping` so it uses the native `http2` instead of `http2-wrapper`, but this goal is a bit too far right now. 
Closes #97

fix: proxies work correctly in Node v18.17

---

src/index.ts

Closes #101. Apart from hooks, exports TransformHeadersAgent, so that the whole config is completely extensible

feat: add export of hooks and TransformHeadersAgent

---

package-lock.json
package.json
test/live-testing/index.js

Port of the `fingerprint-suite` benchmark for comparing the anti-blocking capabilities of different got versions (`got` vs `got-scraping`).
A quick run shows that the ESM port didn't mess up the antiblocking features in any way, here are the results:
```text
got-scraping@latest (3.2.15)
{ passed: 103, blocked: 21, failed: 15 }
---
got-scraping@4.0.0
{ passed: 103, blocked: 20, failed: 16 }
---
got@13.0.0
{ passed: 69, blocked: 0, failed: 70 }
```
@B4nan , @vladfrangu I suppose there is nothing else blocking the release of `got-scraping@4.0.0` then? :)

feat: add Cloudflare blocking benchmarking

---

CHANGELOG.md
package-lock.json
package.json
src/context.ts
src/resolve-protocol.ts
src/types.ts
test/main.test.ts

Fixes https://apifier.slack.com/archives/C02JQSN79V4/p1701858929734429

fix: correct types for got scraping

---

src/hooks/browser-headers.ts
src/hooks/http2.ts
src/resolve-protocol.ts

ALPN negotiation with an unresponsive server caused prolonged hangs, as it didn't respect the specified timeouts.
Fixes #130

fix: pass the timeout to the `resolveProtocol` calls

---

src/hooks/proxy.ts
test/proxy.test.ts

Previously, HTTP request (`http://example.com/resource`) over HTTPS proxy (`https://proxy.com`) was sent as:
- HTTP GET -> `https://proxy.com/example.com/resource`.
- this causes errors, as we're sending an HTTP request to an HTTPS proxy.
After a discussion with @jirimoravcik , we figured that the "pathname" proxies are a marginal thing (`CONNECT` is more popular nowadays).
This PR fixes that - `got-scraping` now does:
- HTTPS CONNECT -> `https://proxy.com/` -> HTTP GET `http://example.com/resource`.
Yet, there is still this comment:
`// Upstream proxies hang up connections on CONNECT + unsecure HTTP`
maybe @szmarczak knows what that was supposed to mean? 😅 seems dangerously close to what we want to do now.
---
Fixes #126

fix: process http over https proxy correctly

---

package-lock.json
package.json
src/hooks/proxy.ts
src/resolve-protocol.ts
tsconfig.json

Connected to https://github.com/apify/apify-proxy/issues/823.
On an internal proxy error (such as trying to access an invalid or unresolvable URL - e.g. `https://example.comundefined`), the proxy returns a response with the error message. `got-scraping` only logs the length of the message, which is quite useless for most applications.

feat: log CONNECT error response body

---

CHANGELOG.md
package-lock.json
package.json
src/agent/h1-proxy-agent.ts
src/auth.ts
src/hooks/proxy.ts
src/resolve-protocol.ts

Extracts and reuses the `getBasic` helper function. 
Uses this helper to generate the `Basic` authentication header in the `proxy` hooks (before, this was done further down the line by [`http2-wrapper`](https://github.com/szmarczak/http2-wrapper), see the [related issue](https://github.com/szmarczak/http2-wrapper/issues/108)).

fix: consistent proxy auth handling

---

package-lock.json
package.json
src/hooks/fix-decompress.ts

fix: no Brotli decompression on an empty `HEAD` response

---

.github/workflows/check.yml
.github/workflows/release.yml
package-lock.json
package.json

Uses Node 22 in CI for build and testing purposes as discussed under #152 . Updates third-party GitHub Actions to their latest versions. 
Bumps the package version to `4.1.0` to fix the prerelease publish for #151 .

chore(ci): test against Node 22, update GH Actions

---

src/index.ts

In my previous PR, I planned to load this helper from filesystem but I didn't take into account the way the library is bundled is reducing all the code into a single file.
This PR makes possible to just do `import { getAgents } from 'got-scraping')`

fix: export getAgents

---

package-lock.json
package.json

Enable automatic prerelease from CI by bumping the package version in `package.json`.

chore: bump package version

---

README.md

The current `header-generator` links point to the older repository with the deprecated package.

Update `header-generator` links
